import type { NextPage } from "next";
import Head from "next/head";
import { Wrapper } from "../modules/Wrapper";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <main>
          <h1>Vai Corinthians</h1>
        </main>
      </Wrapper>
    </div>
  );
};

export default Home;
